// <auto-generated />
using FoodShop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240120192427_GenerateFakeData")]
    partial class GenerateFakeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FoodShop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("FoodId")
                        .HasColumnType("INT")
                        .HasColumnName("food_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("category_name");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("FoodId");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_category_id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodId = 16,
                            Name = "Fantastic Fresh Mouse"
                        },
                        new
                        {
                            Id = 2,
                            FoodId = 20,
                            Name = "Refined Fresh Ball"
                        },
                        new
                        {
                            Id = 3,
                            FoodId = 44,
                            Name = "Sleek Metal Pants"
                        },
                        new
                        {
                            Id = 4,
                            FoodId = 25,
                            Name = "Small Frozen Chair"
                        },
                        new
                        {
                            Id = 5,
                            FoodId = 44,
                            Name = "Gorgeous Soft Tuna"
                        },
                        new
                        {
                            Id = 6,
                            FoodId = 26,
                            Name = "Tasty Soft Salad"
                        },
                        new
                        {
                            Id = 7,
                            FoodId = 28,
                            Name = "Refined Cotton Chips"
                        },
                        new
                        {
                            Id = 8,
                            FoodId = 15,
                            Name = "Handmade Soft Pizza"
                        },
                        new
                        {
                            Id = 9,
                            FoodId = 31,
                            Name = "Handmade Cotton Towels"
                        },
                        new
                        {
                            Id = 10,
                            FoodId = 26,
                            Name = "Sleek Cotton Cheese"
                        },
                        new
                        {
                            Id = 11,
                            FoodId = 27,
                            Name = "Refined Wooden Chair"
                        },
                        new
                        {
                            Id = 12,
                            FoodId = 40,
                            Name = "Tasty Frozen Chicken"
                        },
                        new
                        {
                            Id = 13,
                            FoodId = 19,
                            Name = "Incredible Metal Sausages"
                        },
                        new
                        {
                            Id = 14,
                            FoodId = 28,
                            Name = "Licensed Steel Salad"
                        },
                        new
                        {
                            Id = 15,
                            FoodId = 19,
                            Name = "Rustic Cotton Computer"
                        },
                        new
                        {
                            Id = 16,
                            FoodId = 27,
                            Name = "Handcrafted Plastic Gloves"
                        },
                        new
                        {
                            Id = 17,
                            FoodId = 20,
                            Name = "Handmade Fresh Bacon"
                        },
                        new
                        {
                            Id = 18,
                            FoodId = 42,
                            Name = "Generic Wooden Fish"
                        },
                        new
                        {
                            Id = 19,
                            FoodId = 41,
                            Name = "Gorgeous Granite Shoes"
                        },
                        new
                        {
                            Id = 20,
                            FoodId = 17,
                            Name = "Refined Soft Shoes"
                        },
                        new
                        {
                            Id = 21,
                            FoodId = 27,
                            Name = "Small Granite Shirt"
                        },
                        new
                        {
                            Id = 22,
                            FoodId = 21,
                            Name = "Ergonomic Soft Table"
                        },
                        new
                        {
                            Id = 23,
                            FoodId = 49,
                            Name = "Rustic Metal Towels"
                        },
                        new
                        {
                            Id = 24,
                            FoodId = 45,
                            Name = "Tasty Steel Towels"
                        },
                        new
                        {
                            Id = 25,
                            FoodId = 13,
                            Name = "Rustic Soft Ball"
                        },
                        new
                        {
                            Id = 26,
                            FoodId = 7,
                            Name = "Ergonomic Fresh Fish"
                        },
                        new
                        {
                            Id = 27,
                            FoodId = 30,
                            Name = "Intelligent Cotton Bike"
                        },
                        new
                        {
                            Id = 28,
                            FoodId = 2,
                            Name = "Tasty Plastic Mouse"
                        },
                        new
                        {
                            Id = 29,
                            FoodId = 39,
                            Name = "Gorgeous Concrete Bacon"
                        },
                        new
                        {
                            Id = 30,
                            FoodId = 4,
                            Name = "Unbranded Granite Hat"
                        },
                        new
                        {
                            Id = 31,
                            FoodId = 5,
                            Name = "Licensed Plastic Pizza"
                        },
                        new
                        {
                            Id = 32,
                            FoodId = 2,
                            Name = "Ergonomic Wooden Towels"
                        },
                        new
                        {
                            Id = 33,
                            FoodId = 17,
                            Name = "Small Frozen Pizza"
                        },
                        new
                        {
                            Id = 34,
                            FoodId = 14,
                            Name = "Refined Wooden Computer"
                        },
                        new
                        {
                            Id = 35,
                            FoodId = 33,
                            Name = "Rustic Metal Mouse"
                        },
                        new
                        {
                            Id = 36,
                            FoodId = 40,
                            Name = "Ergonomic Soft Hat"
                        },
                        new
                        {
                            Id = 37,
                            FoodId = 32,
                            Name = "Unbranded Fresh Ball"
                        },
                        new
                        {
                            Id = 38,
                            FoodId = 31,
                            Name = "Unbranded Steel Shirt"
                        },
                        new
                        {
                            Id = 39,
                            FoodId = 15,
                            Name = "Intelligent Steel Tuna"
                        },
                        new
                        {
                            Id = 40,
                            FoodId = 47,
                            Name = "Awesome Rubber Bacon"
                        },
                        new
                        {
                            Id = 41,
                            FoodId = 24,
                            Name = "Awesome Metal Chair"
                        },
                        new
                        {
                            Id = 42,
                            FoodId = 47,
                            Name = "Fantastic Steel Gloves"
                        },
                        new
                        {
                            Id = 43,
                            FoodId = 39,
                            Name = "Rustic Frozen Pizza"
                        },
                        new
                        {
                            Id = 44,
                            FoodId = 9,
                            Name = "Practical Granite Table"
                        },
                        new
                        {
                            Id = 45,
                            FoodId = 40,
                            Name = "Incredible Fresh Hat"
                        },
                        new
                        {
                            Id = 46,
                            FoodId = 31,
                            Name = "Small Frozen Ball"
                        },
                        new
                        {
                            Id = 47,
                            FoodId = 12,
                            Name = "Handmade Plastic Chips"
                        },
                        new
                        {
                            Id = 48,
                            FoodId = 38,
                            Name = "Fantastic Cotton Pants"
                        },
                        new
                        {
                            Id = 49,
                            FoodId = 38,
                            Name = "Incredible Soft Sausages"
                        },
                        new
                        {
                            Id = 50,
                            FoodId = 11,
                            Name = "Gorgeous Soft Pizza"
                        });
                });

            modelBuilder.Entity("FoodShop.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("food_id");

                    b.Property<sbyte>("IsHealthy")
                        .HasColumnType("TINYINT")
                        .HasColumnName("is_healthy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("food_name");

                    b.HasKey("Id")
                        .HasName("pk_food");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_food_id");

                    b.ToTable("foods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsHealthy = (sbyte)1,
                            Name = "Unbranded Rubber Shirt"
                        },
                        new
                        {
                            Id = 2,
                            IsHealthy = (sbyte)1,
                            Name = "Awesome Wooden Table"
                        },
                        new
                        {
                            Id = 3,
                            IsHealthy = (sbyte)0,
                            Name = "Fantastic Fresh Pizza"
                        },
                        new
                        {
                            Id = 4,
                            IsHealthy = (sbyte)1,
                            Name = "Refined Granite Shirt"
                        },
                        new
                        {
                            Id = 5,
                            IsHealthy = (sbyte)1,
                            Name = "Practical Concrete Pizza"
                        },
                        new
                        {
                            Id = 6,
                            IsHealthy = (sbyte)1,
                            Name = "Intelligent Metal Shirt"
                        },
                        new
                        {
                            Id = 7,
                            IsHealthy = (sbyte)1,
                            Name = "Intelligent Plastic Chicken"
                        },
                        new
                        {
                            Id = 8,
                            IsHealthy = (sbyte)1,
                            Name = "Licensed Plastic Pizza"
                        },
                        new
                        {
                            Id = 9,
                            IsHealthy = (sbyte)1,
                            Name = "Intelligent Concrete Gloves"
                        },
                        new
                        {
                            Id = 10,
                            IsHealthy = (sbyte)1,
                            Name = "Ergonomic Metal Shoes"
                        },
                        new
                        {
                            Id = 11,
                            IsHealthy = (sbyte)1,
                            Name = "Unbranded Steel Chips"
                        },
                        new
                        {
                            Id = 12,
                            IsHealthy = (sbyte)0,
                            Name = "Licensed Steel Ball"
                        },
                        new
                        {
                            Id = 13,
                            IsHealthy = (sbyte)1,
                            Name = "Tasty Frozen Bacon"
                        },
                        new
                        {
                            Id = 14,
                            IsHealthy = (sbyte)0,
                            Name = "Generic Soft Computer"
                        },
                        new
                        {
                            Id = 15,
                            IsHealthy = (sbyte)0,
                            Name = "Incredible Frozen Soap"
                        },
                        new
                        {
                            Id = 16,
                            IsHealthy = (sbyte)0,
                            Name = "Intelligent Wooden Mouse"
                        },
                        new
                        {
                            Id = 17,
                            IsHealthy = (sbyte)0,
                            Name = "Generic Wooden Soap"
                        },
                        new
                        {
                            Id = 18,
                            IsHealthy = (sbyte)0,
                            Name = "Ergonomic Concrete Hat"
                        },
                        new
                        {
                            Id = 19,
                            IsHealthy = (sbyte)1,
                            Name = "Awesome Rubber Salad"
                        },
                        new
                        {
                            Id = 20,
                            IsHealthy = (sbyte)0,
                            Name = "Rustic Concrete Keyboard"
                        },
                        new
                        {
                            Id = 21,
                            IsHealthy = (sbyte)0,
                            Name = "Generic Frozen Chair"
                        },
                        new
                        {
                            Id = 22,
                            IsHealthy = (sbyte)0,
                            Name = "Incredible Wooden Chips"
                        },
                        new
                        {
                            Id = 23,
                            IsHealthy = (sbyte)1,
                            Name = "Sleek Soft Bike"
                        },
                        new
                        {
                            Id = 24,
                            IsHealthy = (sbyte)1,
                            Name = "Handcrafted Cotton Bacon"
                        },
                        new
                        {
                            Id = 25,
                            IsHealthy = (sbyte)1,
                            Name = "Gorgeous Wooden Tuna"
                        },
                        new
                        {
                            Id = 26,
                            IsHealthy = (sbyte)0,
                            Name = "Refined Granite Cheese"
                        },
                        new
                        {
                            Id = 27,
                            IsHealthy = (sbyte)1,
                            Name = "Tasty Frozen Car"
                        },
                        new
                        {
                            Id = 28,
                            IsHealthy = (sbyte)1,
                            Name = "Rustic Granite Computer"
                        },
                        new
                        {
                            Id = 29,
                            IsHealthy = (sbyte)1,
                            Name = "Awesome Rubber Shirt"
                        },
                        new
                        {
                            Id = 30,
                            IsHealthy = (sbyte)0,
                            Name = "Generic Frozen Shoes"
                        },
                        new
                        {
                            Id = 31,
                            IsHealthy = (sbyte)1,
                            Name = "Awesome Plastic Salad"
                        },
                        new
                        {
                            Id = 32,
                            IsHealthy = (sbyte)0,
                            Name = "Incredible Metal Soap"
                        },
                        new
                        {
                            Id = 33,
                            IsHealthy = (sbyte)1,
                            Name = "Gorgeous Fresh Tuna"
                        },
                        new
                        {
                            Id = 34,
                            IsHealthy = (sbyte)0,
                            Name = "Licensed Rubber Shirt"
                        },
                        new
                        {
                            Id = 35,
                            IsHealthy = (sbyte)1,
                            Name = "Small Soft Shirt"
                        },
                        new
                        {
                            Id = 36,
                            IsHealthy = (sbyte)1,
                            Name = "Ergonomic Cotton Chicken"
                        },
                        new
                        {
                            Id = 37,
                            IsHealthy = (sbyte)1,
                            Name = "Unbranded Concrete Shoes"
                        },
                        new
                        {
                            Id = 38,
                            IsHealthy = (sbyte)0,
                            Name = "Refined Fresh Chair"
                        },
                        new
                        {
                            Id = 39,
                            IsHealthy = (sbyte)0,
                            Name = "Practical Frozen Tuna"
                        },
                        new
                        {
                            Id = 40,
                            IsHealthy = (sbyte)0,
                            Name = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 41,
                            IsHealthy = (sbyte)0,
                            Name = "Unbranded Cotton Gloves"
                        },
                        new
                        {
                            Id = 42,
                            IsHealthy = (sbyte)0,
                            Name = "Licensed Soft Ball"
                        },
                        new
                        {
                            Id = 43,
                            IsHealthy = (sbyte)0,
                            Name = "Intelligent Cotton Ball"
                        },
                        new
                        {
                            Id = 44,
                            IsHealthy = (sbyte)0,
                            Name = "Sleek Wooden Tuna"
                        },
                        new
                        {
                            Id = 45,
                            IsHealthy = (sbyte)1,
                            Name = "Sleek Granite Car"
                        },
                        new
                        {
                            Id = 46,
                            IsHealthy = (sbyte)0,
                            Name = "Tasty Frozen Keyboard"
                        },
                        new
                        {
                            Id = 47,
                            IsHealthy = (sbyte)1,
                            Name = "Handmade Rubber Chicken"
                        },
                        new
                        {
                            Id = 48,
                            IsHealthy = (sbyte)1,
                            Name = "Awesome Fresh Fish"
                        },
                        new
                        {
                            Id = 49,
                            IsHealthy = (sbyte)0,
                            Name = "Intelligent Plastic Bacon"
                        },
                        new
                        {
                            Id = 50,
                            IsHealthy = (sbyte)0,
                            Name = "Unbranded Concrete Table"
                        });
                });

            modelBuilder.Entity("FoodShop.Domain.Entities.FoodTypicalPlace", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("INT")
                        .HasColumnName("food_id");

                    b.Property<int>("TypicalPlaceId")
                        .HasColumnType("INT")
                        .HasColumnName("typical_place_id");

                    b.HasKey("FoodId", "TypicalPlaceId")
                        .HasName("pk_foods_typical_places");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("idx_food_id_foods_typical_places");

                    b.HasIndex("TypicalPlaceId");

                    b.ToTable("foods_typical_places", (string)null);

                    b.HasData(
                        new
                        {
                            FoodId = 48,
                            TypicalPlaceId = 35
                        },
                        new
                        {
                            FoodId = 20,
                            TypicalPlaceId = 5
                        },
                        new
                        {
                            FoodId = 9,
                            TypicalPlaceId = 40
                        },
                        new
                        {
                            FoodId = 13,
                            TypicalPlaceId = 14
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 26
                        },
                        new
                        {
                            FoodId = 7,
                            TypicalPlaceId = 15
                        },
                        new
                        {
                            FoodId = 38,
                            TypicalPlaceId = 9
                        },
                        new
                        {
                            FoodId = 3,
                            TypicalPlaceId = 34
                        },
                        new
                        {
                            FoodId = 19,
                            TypicalPlaceId = 21
                        },
                        new
                        {
                            FoodId = 37,
                            TypicalPlaceId = 8
                        },
                        new
                        {
                            FoodId = 36,
                            TypicalPlaceId = 18
                        },
                        new
                        {
                            FoodId = 49,
                            TypicalPlaceId = 49
                        },
                        new
                        {
                            FoodId = 47,
                            TypicalPlaceId = 18
                        },
                        new
                        {
                            FoodId = 24,
                            TypicalPlaceId = 7
                        },
                        new
                        {
                            FoodId = 30,
                            TypicalPlaceId = 45
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 22
                        },
                        new
                        {
                            FoodId = 38,
                            TypicalPlaceId = 2
                        },
                        new
                        {
                            FoodId = 15,
                            TypicalPlaceId = 2
                        },
                        new
                        {
                            FoodId = 46,
                            TypicalPlaceId = 28
                        },
                        new
                        {
                            FoodId = 31,
                            TypicalPlaceId = 22
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 11
                        },
                        new
                        {
                            FoodId = 18,
                            TypicalPlaceId = 28
                        },
                        new
                        {
                            FoodId = 4,
                            TypicalPlaceId = 8
                        },
                        new
                        {
                            FoodId = 43,
                            TypicalPlaceId = 30
                        },
                        new
                        {
                            FoodId = 37,
                            TypicalPlaceId = 30
                        },
                        new
                        {
                            FoodId = 32,
                            TypicalPlaceId = 37
                        },
                        new
                        {
                            FoodId = 7,
                            TypicalPlaceId = 14
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 14
                        },
                        new
                        {
                            FoodId = 37,
                            TypicalPlaceId = 41
                        },
                        new
                        {
                            FoodId = 43,
                            TypicalPlaceId = 4
                        },
                        new
                        {
                            FoodId = 17,
                            TypicalPlaceId = 12
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 9
                        },
                        new
                        {
                            FoodId = 45,
                            TypicalPlaceId = 4
                        },
                        new
                        {
                            FoodId = 16,
                            TypicalPlaceId = 42
                        },
                        new
                        {
                            FoodId = 19,
                            TypicalPlaceId = 5
                        },
                        new
                        {
                            FoodId = 26,
                            TypicalPlaceId = 46
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 1
                        },
                        new
                        {
                            FoodId = 30,
                            TypicalPlaceId = 20
                        },
                        new
                        {
                            FoodId = 24,
                            TypicalPlaceId = 14
                        },
                        new
                        {
                            FoodId = 15,
                            TypicalPlaceId = 31
                        },
                        new
                        {
                            FoodId = 27,
                            TypicalPlaceId = 43
                        },
                        new
                        {
                            FoodId = 25,
                            TypicalPlaceId = 26
                        },
                        new
                        {
                            FoodId = 13,
                            TypicalPlaceId = 12
                        },
                        new
                        {
                            FoodId = 30,
                            TypicalPlaceId = 18
                        },
                        new
                        {
                            FoodId = 30,
                            TypicalPlaceId = 6
                        },
                        new
                        {
                            FoodId = 45,
                            TypicalPlaceId = 1
                        },
                        new
                        {
                            FoodId = 31,
                            TypicalPlaceId = 39
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 49
                        },
                        new
                        {
                            FoodId = 40,
                            TypicalPlaceId = 36
                        },
                        new
                        {
                            FoodId = 39,
                            TypicalPlaceId = 47
                        });
                });

            modelBuilder.Entity("FoodShop.Domain.Entities.TypicalPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("country_name");

                    b.HasKey("Id")
                        .HasName("pk_typical_place");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_typical_place_id");

                    b.ToTable("typical_places", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "El Salvador"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Cyprus"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Svalbard & Jan Mayen Islands"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Serbia"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Central African Republic"
                        },
                        new
                        {
                            Id = 6,
                            Country = "American Samoa"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Norfolk Island"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Burkina Faso"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Bulgaria"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Saint Barthelemy"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Austria"
                        },
                        new
                        {
                            Id = 12,
                            Country = "French Polynesia"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Sweden"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Malawi"
                        },
                        new
                        {
                            Id = 15,
                            Country = "United States of America"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Netherlands"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Nauru"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Niue"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Dominica"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Country = "Sierra Leone"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 23,
                            Country = "Greece"
                        },
                        new
                        {
                            Id = 24,
                            Country = "Albania"
                        },
                        new
                        {
                            Id = 25,
                            Country = "Bahamas"
                        },
                        new
                        {
                            Id = 26,
                            Country = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 27,
                            Country = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 28,
                            Country = "Turkey"
                        },
                        new
                        {
                            Id = 29,
                            Country = "Nauru"
                        },
                        new
                        {
                            Id = 30,
                            Country = "Western Sahara"
                        },
                        new
                        {
                            Id = 31,
                            Country = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 32,
                            Country = "Slovenia"
                        },
                        new
                        {
                            Id = 33,
                            Country = "Cuba"
                        },
                        new
                        {
                            Id = 34,
                            Country = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 35,
                            Country = "Nauru"
                        },
                        new
                        {
                            Id = 36,
                            Country = "Hong Kong"
                        },
                        new
                        {
                            Id = 37,
                            Country = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 38,
                            Country = "Malta"
                        },
                        new
                        {
                            Id = 39,
                            Country = "New Zealand"
                        },
                        new
                        {
                            Id = 40,
                            Country = "Palau"
                        },
                        new
                        {
                            Id = 41,
                            Country = "Mauritania"
                        },
                        new
                        {
                            Id = 42,
                            Country = "Guadeloupe"
                        },
                        new
                        {
                            Id = 43,
                            Country = "Germany"
                        },
                        new
                        {
                            Id = 44,
                            Country = "Tuvalu"
                        },
                        new
                        {
                            Id = 45,
                            Country = "Latvia"
                        },
                        new
                        {
                            Id = 46,
                            Country = "Seychelles"
                        },
                        new
                        {
                            Id = 47,
                            Country = "Mozambique"
                        },
                        new
                        {
                            Id = 48,
                            Country = "Macao"
                        },
                        new
                        {
                            Id = 49,
                            Country = "Djibouti"
                        },
                        new
                        {
                            Id = 50,
                            Country = "New Caledonia"
                        });
                });

            modelBuilder.Entity("FoodShop.Domain.Entities.Category", b =>
                {
                    b.HasOne("FoodShop.Domain.Entities.Food", "Food")
                        .WithMany("Categories")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_foods");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodShop.Domain.Entities.FoodTypicalPlace", b =>
                {
                    b.HasOne("FoodShop.Domain.Entities.Food", "Food")
                        .WithMany("FoodTypicalPlaces")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_typical_places_food_typical_places");

                    b.HasOne("FoodShop.Domain.Entities.TypicalPlace", "TypicalPlace")
                        .WithMany("FoodTypicalPlaces")
                        .HasForeignKey("TypicalPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("TypicalPlace");
                });

            modelBuilder.Entity("FoodShop.Domain.Entities.Food", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("FoodTypicalPlaces");
                });

            modelBuilder.Entity("FoodShop.Domain.Entities.TypicalPlace", b =>
                {
                    b.Navigation("FoodTypicalPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
